### PR TITLE
Promote `item.tags` as a full-fledged yaml array

### PR DESCRIPTION
**Pull request by agirivera**
## Summary of changes
- Promotes `item.tags` as a full-fledged yaml array to avoid json quoting issues
- Updates documentation to reflect change

/fyi: @juwai/platform-all Please review. Thanks.

### CODE REVIEW

**Comment by tjoelsson** [comment]
Will this work with existing configuration files?

**Comment by agirivera** [comment]
No. I've updated the rpc related ones. I found ansible is not consistent in quoting when `{{ }}` are present in a string. This causes consul to error sometimes.

**Comment by tjoelsson** [comment]
Please link PRs that depend on each other.

**Comment by tjoelsson** [comment]
👍

**Comment by stuartwan** [comment]
👍

**Comment by agirivera** [comment]
Reimported on ansible-galaxy.

**Pull request merged**
